### PR TITLE
[WIP] Add ethers guide

### LINKED ISSUE #622: Add ethers.js Guide and snippets

### PR DESCRIPTION
**Pull request by jribbink**
closes #622 
WIP, not ready yet.  Just making a draft PR for this so I can see preview.

blocked by
 - https://github.com/onflow/flow-evm-gateway/pull/137

### CODE REVIEW

**Comment by jribbink** [comment]
This is currently blocked by https://github.com/onflow/flow-evm-gateway/pull/137

**Comment by gregsantos** [comment]
all good here now, yeah @jribbink ?

**Comment by jribbink** [comment]
We have another issue now @gregsantos https://github.com/onflow/flow-evm-gateway/issues/145

There are some missing fields in the `Block` model in the `flow-evm-gateway`, and `ethers` throws because of this when trying to fetch blocks.  At a minimum these fields need to be populated with empty values to produce a working example.

**Comment by bthaile** [comment]
simple Note: once a flow chain PR is merged to view we can add a `viem.md` file in clients directory.

**Comment by franklywatson** [comment]
Looks like this was pulled in with https://github.com/onflow/docs/pull/847/files#diff-4a78348a0c7360742a26472f99efbac19d75a22724947f25d2bc4c3ce4a8321a

**Pull request closed without merging**
