### PR TITLE
Update Borrow function in NFT Docs

### PR DESCRIPTION
**Pull request by DappCoderr**
In the Collection resource borrowNFT_  function gives an error.
NonFungibleToken type cast to `&{NFT}?` is redundant. 

Solution: To remove this error add Force Unwrap Operator (!).

### CODE REVIEW

**Review by sisyphusSmiling — APPROVED** [review]
Good catch, thanks for the correction!

**Review by joshuahannan — COMMENTED** [review]
I don't think this is correct. This function is supposed to return an optional, so we should not be force unwrapping it here. See [ExampleNFT](https://github.com/onflow/flow-nft/blob/master/contracts/ExampleNFT.cdc#L226) for the correct implementation.

@DappCoderr Can you explain what you're trying to do here? Maybe I'm not understanding

**Comment by joshuahannan** [comment]
That isn't an error, it is just a warning, so the contract will still deploy if you ignore it. 

That is just pointing out that the entire cast is redundant, not the `?`, if you just remove the cast completely, it will work properly.

```
        access(all) view fun borrowNFT(_ id: UInt64): &{NonFungibleToken.NFT}? {
            return &self.ownedNFTs[id]
        }
```

Can you update the PR to just have that? Thank you!

**Comment by DappCoderr** [comment]
Thanks for the clarification, @joshuahannan 
I'll remove the redundant cast and push the updated PR.

**Review by joshuahannan — APPROVED** [review]

**Pull request merged**
