### PR TITLE
Nialexsan/remove cadence

### PR DESCRIPTION
**Pull request by nialexsan**
removed cadence docs and set up redirects to https://cadence-lang.org/docs/0.42/

### CODE REVIEW

**Comment by turbolent** [comment]
Blocked on #439

**Comment by nialexsan** [comment]
blocked by https://github.com/onflow/cadence-lang.org/pull/17

**Review by turbolent — COMMENTED** [review]
Looks good! 🎉 

The only thing left to be done is to redirect to just `/docs`, not `/docs/0.42` anymore. This changed recently, so that links don't become outdated, but always point to the currently released docs by default.

**Comment by nialexsan** [comment]
@turbolent, fixed the redirect and links

**Review by turbolent — APPROVED** [review]
🎉

**Pull request merged**
