### PR TITLE
docs: update communtity resources

### PR DESCRIPTION
**Pull request by btspoony**
- add quicknode articles
- fix some links in projects
- add Flowdiver historical API to projects
- re-order wallets, prioritize frw.
- add LearnWeb3 Flow Faucet

### CODE REVIEW

**Comment by nialexsan** [comment]
we'll be removing articles from the docs until we refactor the view
cc: @Aliserag

**Review by nialexsan — APPROVED** [review]

**Comment by btspoony** [comment]
> we'll be removing articles from the docs until we refactor the view cc: @Aliserag

So are we supposed to update the community resources after the articles view is refactored it?

**Comment by nialexsan** [comment]
yes, you still can add new articles into the list, we'll be refactoring the view and remove some obsolete articles, but the articles page will be restored in the future

**Comment by nialexsan** [comment]
@btspoony could you please resolve the merge conflict?
`src/data/pages/learn.ts` has been removed until further refactoring

**Comment by btspoony** [comment]
> @btspoony could you please resolve the merge conflict? `src/data/pages/learn.ts` has been removed until further refactoring

Resolved

**Review by turbolent — APPROVED** [review]

**Pull request merged**
