### PR TITLE
Add documentation for AuthAccount.check

### PR DESCRIPTION
**Pull request by darkdrag00nv2**
Depends on https://github.com/onflow/cadence/pull/2492
Work towards https://github.com/onflow/developer-grants/issues/179

### CODE REVIEW

**Review by bthaile — APPROVED** [review]
lgtm

**Comment by darkdrag00nv2** [comment]
@nialexsan Can you revert this please? The main functionality is not merged in Cadence yet. I opened the code (https://github.com/onflow/cadence/pull/2492) + doc changes in parallel.

cc: @turbolent

**Comment by turbolent** [comment]
@nialexsan this should have not been merged, see the dependency

**Comment by turbolent** [comment]
Reverted in #82. @darkdrag00nv2 can you please re-open this PR?

**Pull request merged**
